setwd("C:/Users/CHENCX9/Documents/_LEARNING/_Statistical Research/Visual Analytics for Safety Data/Tendril Plot")
library(devtools)
library(bindr)
library(dplyr)
#devtools::install_github("karpefors/Tendril",force=T)
library(Tendril)
data("TendrilData")
test <- Tendril(mydata=TendrilData, rotations=Rotations, AEfreqTreshold=9, Tag="Comment", Treatments=c("placebo", "active"), Unique.Subject.Identifier="subjid", Term="ae", Treat="treatment", StartDay="day", SubjList=SubjList, SubjList.subject="subjid", SubjList.treatment="treatment")
plot(test,type="basic")
plot(test,type="basic",coloring="p.adj")

